### ISSUE TITLE
ImportError: cannot import name 'DeclarativeBase' from 'sqlalchemy.orm'

### ISSUE THREAD

**Issue by bsce20007** [apache/iceberg-python#1514]
### Apache Iceberg version

0.8.1 (latest release)

### Please describe the bug 🐞

I’m facing an issue where PyIceberg’s usage of SQLAlchemy 2.x is causing compatibility problems with Apache Airflow, which only supports SQLAlchemy 1.4.x. Specifically, I’m getting an ImportError: cannot import name 'DeclarativeBase' from 'sqlalchemy.orm' when running a DAG that uses PyIceberg. This issue occurs because PyIceberg expects SQLAlchemy 2.x, but I’m forced to use SQLAlchemy 1.4.x for compatibility with Airflow. Any advice on resolving this conflict or workarounds to make PyIceberg work with SQLAlchemy 1.4.x while maintaining Airflow functionality would be greatly appreciated.

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [x] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

**Comment by kevinjqliu** [comment]
> Airflow. Any advice on resolving this conflict or workarounds to make PyIceberg work with SQLAlchemy 1.4.x while maintaining Airflow functionality would be greatly appreciated.

I think you would either have to change Airflow or PyIceberg. 

You might be able to change PyIceberg to use SQLAlchemy 1.x but I'm not sure if it'll be compatible. Historically, we have been using 2.x https://github.com/apache/iceberg-python/pulls?q=is%3Apr+SQLAlchemy+is%3Aclosed

Otherwise you might have to upgrade Airflow to align with PyIceberg

**Comment by jayceslesar** [comment]
Looks like airflow is slated to use 2.x in 3.0 release https://github.com/apache/airflow/issues/39593

**Comment by chespinoza** [comment]
@bsce20007 If you are using pyiceberg in an Airflow pipeline, you should be able (it's a good practice) to isolate your dependencies using the correct setup for your operator. I've done this with the Python operator and Beam Operator, and of course, you also have the Docker operator.
