### PR TITLE
dep: disallow pydantic 2.12.0 and 2.12.1, update poetry lock to use pydantic 2.12.3

### LINKED ISSUE #2590: Upstream Pydantic 2.12.0 has a Regression that will break PyIceberg
### Apache Iceberg version

None

### Please describe the bug 🐞

Pydantic recently `2.12.0` and unfortunately it contains a regression: https://github.com/pydantic/pydantic/issues/12347 that `ValidationInfo` object will lose `field_names` in some cases.

I have a draft PR that experiments `2.12.0` and confirmed that the regression affect us: https://github.com/apache/iceberg-python/pull/2589
```

table_metadata = ValidationInfo(config={'title': 'TableMetadataV2', 'validate_by_alias': True, 'validate_by_name': True}, context=None, data=None, field_name=None)

    def check_schemas(table_metadata: TableMetadata) -> TableMetadata:
        """Check if the current-schema-id is actually present in schemas."""
>       current_schema_id = table_metadata.current_schema_id
E       AttributeError: 'pydantic_core._pydantic_core.ValidationInfo' object has no attribute 'current_schema_id'
```

More info:
`pydantic 2.11.10`

Image

`pydantic 2.12.0`

Image

While waiting for upstream fix, I think we may want to pin the pydantic version to `<2.12.0`

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by kevinjqliu**
# Rationale for this change
Follow up to #2591
Closes #2590

Pydantic released a regression in 2.12.x that was fixed by 2.12.2 and 2.12.3
2.12.2 originally did not work due to incompatible signature that was fixed in #2626
2.12.3 turn the incompatible signature into a deprecation warning. 

This PR disallows pydantic 2.12.0 and 2.12.1 and update poetry lock to use pydantic 2.12.3

With #2626 merged, pyiceberg should work with both pydantic 2.12.2 and 2.12.3

## Are these changes tested?
Yes, UT.
Tested both with pydantic 2.12.2 and 2.12.3

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by kevinjqliu** [comment]
Running CI once for pydantic 2.12.2 and again for 2.12.3
